name: Tests

on:
  push:
    branches: [main]
    paths:
       - 'src/*'  
       - 'include/*'
       - 'makefile'
  pull_request:
    branches: [main]
    paths:
       - 'src/*' 
       - 'include/*'
       - 'makefile'

jobs:
    
    build-and-test:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
      
        - name: Update Environment
          run: sudo apt-get update && sudo apt-get install -y g++ make

        - name: Test
          run: make test

        - name: Clean
          if: always() # Always run this step, even if the previous steps fail
          run: make clean

        

